
DROP USER CCF_PREMIO_PEMBERTON_TST_OWN CASCADE;
DROP USER CCVCUP3_DEV_OWN CASCADE;
DROP USER CSB_FANTA_AVENTURA_DEV_WEB CASCADE;
DROP USER CCV_PROMO_MUSIC_TST_OWN CASCADE;
DROP USER CCV_COVERMIX_MOTHER_INT_WEB CASCADE;
DROP USER CCF_COLETIVO_BUILD CASCADE;
DROP USER BCCDEBOWN CASCADE;
DROP USER PROMOMUSIC_TST_WEB CASCADE;
DROP USER CC_STICKER_BUILD CASCADE;
DROP USER CNC_BRN_MAG_DEV_WEB CASCADE;
DROP USER DLV_TRADEMARK_TST_OWN CASCADE;
DROP USER CCV_CUP_COLOR_TST_WEB CASCADE;
DROP USER PROMOMUSIC_DEV_OWN CASCADE;
DROP USER BBINFO CASCADE;
DROP USER CNC_BRN_MAG_BUILD CASCADE;
DROP USER CCV_NATAL_DEV_OWN CASCADE;
DROP USER CC_TRIPS_INT_WEB CASCADE;
DROP USER BBCARREGADORES CASCADE;
DROP USER CC_CONFCUP_OWN_INT CASCADE;
DROP USER PEMBERTON_HOM_BUILD CASCADE;
DROP USER CC_TRIPS_DEV_OWN CASCADE;
DROP USER CC_STICKER_INT_WEB CASCADE;
DROP USER CCV_MOBILE_TST_WEB CASCADE;
DROP USER CCV_XMAS_TRIP_DEV_WEB CASCADE;
DROP USER CCV_NATAL_DEV_WEB CASCADE;
DROP USER CC_TRIPS_TST_OWN CASCADE;
DROP USER CCV_MOBILE_TST_OWN CASCADE;
DROP USER CCV_XMAS_TRIP_DEV_OWN CASCADE;
DROP USER CCV_NATAL_BUILD CASCADE;
DROP USER CC_MANIF_INT_WEB CASCADE;
DROP USER CCVCUP3_TST_WEB CASCADE;
DROP USER DLV_TRADEMARK_INT_OWN CASCADE;
DROP USER CCV_NATAL_TST_OWN CASCADE;
DROP USER CCV_COVERMIX_MOTHER_TST_OWN CASCADE;
DROP USER CSB_SCHWEPPES_TST_OWN CASCADE;
DROP USER CCF_COLETIVO_DEV_OWN CASCADE;
DROP USER CCF_SAAC_DEV_OWN CASCADE;
DROP USER CCV_PROMO_MUSIC_BUILD CASCADE;
DROP USER PEMPERTON_DUMP_HOM CASCADE;
DROP USER CC_STICKER_INT_OWN CASCADE;
DROP USER CC_SCHWEPPES_PLAY_INT_WEB CASCADE;
DROP USER PROMOMUSIC_INT_OWN CASCADE;
DROP USER PROMOMUSIC_DEV_WEB CASCADE;
DROP USER CCV_COVERMIX_MOTHER_DEV_OWN CASCADE;
DROP USER DLV_TRADEMARK_BUILD CASCADE;
DROP USER CCV_MOBILE_DEV_WEB CASCADE;
DROP USER PROMOMUSIC_BUILD CASCADE;
DROP USER CC_CCZRIR_BUILD CASCADE;
DROP USER CCF_COLETIVO_TST_OWN CASCADE;
DROP USER CC_KUAT_HISTORY_BUILD CASCADE;
DROP USER CSB_SCHWEPPES_INT_OWN CASCADE;
DROP USER CC_CONFCUP_OWN_DEV CASCADE;
DROP USER CSB_FANTA_AVENTURA_INT_OWN CASCADE;
DROP USER CCV_COVERMIX_MOTHER_DUMP CASCADE;
DROP USER COCACOKESIDE CASCADE;
DROP USER CCV_MOBILE_DEV_OWN CASCADE;
DROP USER CC_CONFCUP_WEB_INT CASCADE;
DROP USER CC_KUAT_HISTORY_TST_WEB CASCADE;
DROP USER CSB_SCHWEPPES_INT_WEB CASCADE;
DROP USER CCF_SAAC_TST_OWN CASCADE;
DROP USER CC_MANIF_DEV_OWN CASCADE;
DROP USER CCV_CUP_COLOR_INT_OWN CASCADE;
DROP USER CC_KUAT_HISTORY_DEV_WEB CASCADE;
DROP USER CSB_FANTA_AVENTURA_DEV_OWN CASCADE;
DROP USER COLETIVO CASCADE;
DROP USER CCV_CUP_COLOR_DEV_WEB CASCADE;
DROP USER CCVCUP3_TST_OWN CASCADE;
DROP USER CCV_COVERMIX_MOTHER_DEV_WEB CASCADE;
DROP USER PEMBERTON_HOM_INT_OWN CASCADE;
DROP USER CCF_PREMIO_PEMBERTON_INT_OWN CASCADE;
DROP USER CC_STICKER_DEV_WEB CASCADE;
DROP USER CCFANTAPWP CASCADE;
DROP USER CSB_FANTA_AVENTURA_INT_WEB CASCADE;
DROP USER CCV_PROMO_MUSIC_INT_WEB CASCADE;
DROP USER CNC_BRN_MAG_INT_OWN CASCADE;
DROP USER CC_TRIPS_DEV_WEB CASCADE;
DROP USER CC_KUAT_HISTORY_DEV_OWN CASCADE;
DROP USER CSB_SCHWEPPES_DEV_WEB CASCADE;
DROP USER CC_STICKER_TST_WEB CASCADE;
DROP USER CCSPRITE_NEW CASCADE;
DROP USER CCF_SAAC_INT_OWN CASCADE;
DROP USER CCV_PROMO_MUSIC_TST_WEB CASCADE;
DROP USER CCF_COLETIVO_RC_OWN CASCADE;
DROP USER CSB_FANTA_AVENTURA_TST_OWN CASCADE;
DROP USER TCCCONSUMERS CASCADE;
DROP USER CC_CCZRIR_DEV_OWN CASCADE;
DROP USER CC_MANIF_TST_WEB CASCADE;
DROP USER CCV_CUP_COLOR_BUILD CASCADE;
DROP USER CCV_COVERMIX_MOTHER_INT_OWN CASCADE;
DROP USER CSB_SCHWEPPES_DEV_OWN CASCADE;
DROP USER CROWDPERFINTWEB CASCADE;
DROP USER CSB_FANTA_AVENTURA_BUILD CASCADE;
DROP USER CCV_PROMO_MUSIC_DEV_OWN CASCADE;
DROP USER CNC_BRN_MAG_TST_OWN CASCADE;
DROP USER CCV_MOBILE_INT_OWN CASCADE;
DROP USER CC_CONFCUP_WEB_DEV CASCADE;
DROP USER CC_MANIF_TST_OWN CASCADE;
DROP USER COCACOLA_GESTAO CASCADE;
DROP USER CCF_COLETIVO_TST_WEB CASCADE;
DROP USER CCF_PREMIO_PEMBERTON_DEV_WEB CASCADE;
DROP USER CC_MANIF_BUILD CASCADE;
DROP USER CC_SCHWEPPES_PLAY_INT_OWN CASCADE;
DROP USER CCV_NATAL_INT_OWN CASCADE;
DROP USER CSB_SCHWEPPES_TST_WEB CASCADE;
DROP USER CCF_SAAC_DEV_WEB CASCADE;
DROP USER CCF_COLETIVO_DEV_WEB CASCADE;
DROP USER SPATIAL_CSW_ADMIN_USR CASCADE;
DROP USER PROMOMUSICAOLD CASCADE;
DROP USER CNC_BRN_MAG_DEV_OWN CASCADE;
DROP USER CROWDPERFTSTOWN CASCADE;
DROP USER CC_KUAT_HISTORY_INT_WEB CASCADE;
DROP USER CSB_FANTA_AVENTURA_TST_WEB CASCADE;
DROP USER CCV_PROMO_MUSIC_DEV_WEB CASCADE;
DROP USER CC_CCZRIR_INT_OWN CASCADE;
DROP USER CC_CONFCUP_WEB_TST CASCADE;
DROP USER PEMBERTON_HOM_TST_WEB CASCADE;
DROP USER DLV_TRADEMARK_TST_WEB CASCADE;
DROP USER CCVCUP3_BUILD CASCADE;
DROP USER CROWDPERFDEVWEB CASCADE;
DROP USER CCV_MOBILE_BUILD CASCADE;
DROP USER CCV_CUP_COLOR_DEV_OWN CASCADE;
DROP USER CC_CCZRIR_INT_WEB CASCADE;
DROP USER CCPEMBERTON CASCADE;
DROP USER CC_STICKER_TST_OWN CASCADE;
DROP USER CCV_NATAL_TST_WEB CASCADE;
DROP USER CC_STICKER_DEV_OWN CASCADE;
DROP USER FLOWS_FILES CASCADE;
DROP USER BKP_CARREGADORES CASCADE;
DROP USER CCF_COLETIVO_INT_WEB CASCADE;
DROP USER CCV_MOBILE_INT_WEB CASCADE;
DROP USER CCF_SAAC_TST_WEB CASCADE;
DROP USER PROMOMUSIC_TST_OWN CASCADE;
DROP USER CCV_WORLD_CUP_BUILD CASCADE;
DROP USER CC_MANIF_DEV_WEB CASCADE;
DROP USER CCV_CUP_COLOR_TST_OWN CASCADE;
DROP USER CCF_SAAC_BUILD CASCADE;
DROP USER CROWDPERFDEVOWN CASCADE;
DROP USER CCF_PREMIO_PEMBERTON_TST_WEB CASCADE;
DROP USER CCZSHAREOWN CASCADE;
DROP USER CCF_PREMIO_PEMBERTON_INT_WEB CASCADE;
DROP USER CC_TRIPS_TST_WEB CASCADE;
DROP USER CC_CCZRIR_TST_OWN CASCADE;
DROP USER CCVCUP3_DEV_WEB CASCADE;
DROP USER CC_CONFCUP_BUILD CASCADE;
DROP USER CC_SCHWEPPES_PLAY_DEV_WEB CASCADE;
DROP USER CCF_PREMIO_PEMBERTON_BUILD CASCADE;
DROP USER CC_LIVEPOSITIVELY_TS CASCADE;
DROP USER CC_CCZRIR_DEV_WEB CASCADE;
DROP USER DLV_TRADEMARK_DEV_WEB CASCADE;
DROP USER CCV_COVERMIX_MOTHER_BUILD CASCADE;
DROP USER CC_CONFCUP_OWN_TST CASCADE;
DROP USER CCV_WORLD_CUP_TST_OWN CASCADE;
DROP USER CCV_WORLD_CUP_INT_OWN CASCADE;
DROP USER CCVCUP3_INT_OWN CASCADE;
DROP USER PROMOMUSIC_INT_WEB CASCADE;
DROP USER CCV_WORLD_CUP_TST_WEB CASCADE;
DROP USER CCF_SAAC_INT_WEB CASCADE;
DROP USER CCV_CUP_COLOR_INT_WEB CASCADE;
DROP USER CCV_XMAS_TRIP_TST_OWN CASCADE;
DROP USER CROWDPERFINTOWN CASCADE;
DROP USER CCVLIVDONWEB CASCADE;
DROP USER CCF_PREMIO_PEMBERTON_DEV_OWN CASCADE;
DROP USER DLV_TRADEMARK_DEV_OWN CASCADE;
DROP USER PEMBERTON_HOM_INT_WEB CASCADE;
DROP USER CC_CCZRIR_TST_WEB CASCADE;
DROP USER CCV_XMAS_TRIP_BUILD CASCADE;
DROP USER CCV_WORLD_CUP_INT_WEB CASCADE;
DROP USER CC_KUAT_HISTORY_TST_OWN CASCADE;
DROP USER CCVCUP3_INT_WEB CASCADE;
DROP USER COLETIVO_DUMP_PROD CASCADE;
DROP USER CC_KUAT_HISTORY_INT_OWN CASCADE;
DROP USER CCV_COVERMIX_MOTHER_TST_WEB CASCADE;
DROP USER CCV_WORLD_CUP_DEV_WEB CASCADE;
DROP USER CROWDPERFTSTWEB CASCADE;
DROP USER DLV_TRADEMARK_INT_WEB CASCADE;
DROP USER CCV_XMAS_TRIP_TST_WEB CASCADE;
DROP USER CCF_COLETIVO_INT_OWN CASCADE;

user CCF_PREMIO_PEMBERTON_TST_OWN eliminado.
user CCVCUP3_DEV_OWN eliminado.
user CSB_FANTA_AVENTURA_DEV_WEB eliminado.
user CCV_PROMO_MUSIC_TST_OWN eliminado.
user CCV_COVERMIX_MOTHER_INT_WEB eliminado.
user CCF_COLETIVO_BUILD eliminado.
user BCCDEBOWN eliminado.
user PROMOMUSIC_TST_WEB eliminado.
user CC_STICKER_BUILD eliminado.
user CNC_BRN_MAG_DEV_WEB eliminado.
user DLV_TRADEMARK_TST_OWN eliminado.
user CCV_CUP_COLOR_TST_WEB eliminado.
user PROMOMUSIC_DEV_OWN eliminado.
user BBINFO eliminado.
user CNC_BRN_MAG_BUILD eliminado.
user CCV_NATAL_DEV_OWN eliminado.
user CC_TRIPS_INT_WEB eliminado.
user BBCARREGADORES eliminado.
user CC_CONFCUP_OWN_INT eliminado.
user PEMBERTON_HOM_BUILD eliminado.
user CC_TRIPS_DEV_OWN eliminado.
user CC_STICKER_INT_WEB eliminado.
user CCV_MOBILE_TST_WEB eliminado.
user CCV_XMAS_TRIP_DEV_WEB eliminado.
user CCV_NATAL_DEV_WEB eliminado.
user CC_TRIPS_TST_OWN eliminado.
user CCV_MOBILE_TST_OWN eliminado.
user CCV_XMAS_TRIP_DEV_OWN eliminado.
user CCV_NATAL_BUILD eliminado.
user CC_MANIF_INT_WEB eliminado.
user CCVCUP3_TST_WEB eliminado.
user DLV_TRADEMARK_INT_OWN eliminado.
user CCV_NATAL_TST_OWN eliminado.
user CCV_COVERMIX_MOTHER_TST_OWN eliminado.
user CSB_SCHWEPPES_TST_OWN eliminado.
user CCF_COLETIVO_DEV_OWN eliminado.
user CCF_SAAC_DEV_OWN eliminado.
user CCV_PROMO_MUSIC_BUILD eliminado.
user PEMPERTON_DUMP_HOM eliminado.
user CC_STICKER_INT_OWN eliminado.
user CC_SCHWEPPES_PLAY_INT_WEB eliminado.
user PROMOMUSIC_INT_OWN eliminado.
user PROMOMUSIC_DEV_WEB eliminado.
user CCV_COVERMIX_MOTHER_DEV_OWN eliminado.
user DLV_TRADEMARK_BUILD eliminado.
user CCV_MOBILE_DEV_WEB eliminado.
user PROMOMUSIC_BUILD eliminado.
user CC_CCZRIR_BUILD eliminado.
user CCF_COLETIVO_TST_OWN eliminado.
user CC_KUAT_HISTORY_BUILD eliminado.
user CSB_SCHWEPPES_INT_OWN eliminado.
user CC_CONFCUP_OWN_DEV eliminado.
user CSB_FANTA_AVENTURA_INT_OWN eliminado.
user CCV_COVERMIX_MOTHER_DUMP eliminado.
user COCACOKESIDE eliminado.
user CCV_MOBILE_DEV_OWN eliminado.
user CC_CONFCUP_WEB_INT eliminado.
user CC_KUAT_HISTORY_TST_WEB eliminado.
user CSB_SCHWEPPES_INT_WEB eliminado.
user CCF_SAAC_TST_OWN eliminado.
user CC_MANIF_DEV_OWN eliminado.
user CCV_CUP_COLOR_INT_OWN eliminado.
user CC_KUAT_HISTORY_DEV_WEB eliminado.
user CSB_FANTA_AVENTURA_DEV_OWN eliminado.
user COLETIVO eliminado.
user CCV_CUP_COLOR_DEV_WEB eliminado.
user CCVCUP3_TST_OWN eliminado.
user CCV_COVERMIX_MOTHER_DEV_WEB eliminado.
user PEMBERTON_HOM_INT_OWN eliminado.
user CCF_PREMIO_PEMBERTON_INT_OWN eliminado.
user CC_STICKER_DEV_WEB eliminado.
user CCFANTAPWP eliminado.
user CSB_FANTA_AVENTURA_INT_WEB eliminado.
user CCV_PROMO_MUSIC_INT_WEB eliminado.
user CNC_BRN_MAG_INT_OWN eliminado.
user CC_TRIPS_DEV_WEB eliminado.
user CC_KUAT_HISTORY_DEV_OWN eliminado.
user CSB_SCHWEPPES_DEV_WEB eliminado.
user CC_STICKER_TST_WEB eliminado.
user CCSPRITE_NEW eliminado.
user CCF_SAAC_INT_OWN eliminado.
user CCV_PROMO_MUSIC_TST_WEB eliminado.
user CCF_COLETIVO_RC_OWN eliminado.
user CSB_FANTA_AVENTURA_TST_OWN eliminado.
user TCCCONSUMERS eliminado.
user CC_CCZRIR_DEV_OWN eliminado.
user CC_MANIF_TST_WEB eliminado.
user CCV_CUP_COLOR_BUILD eliminado.
user CCV_COVERMIX_MOTHER_INT_OWN eliminado.
user CSB_SCHWEPPES_DEV_OWN eliminado.
user CROWDPERFINTWEB eliminado.
user CSB_FANTA_AVENTURA_BUILD eliminado.
user CCV_PROMO_MUSIC_DEV_OWN eliminado.
user CNC_BRN_MAG_TST_OWN eliminado.
user CCV_MOBILE_INT_OWN eliminado.
user CC_CONFCUP_WEB_DEV eliminado.
user CC_MANIF_TST_OWN eliminado.
user COCACOLA_GESTAO eliminado.
user CCF_COLETIVO_TST_WEB eliminado.
user CCF_PREMIO_PEMBERTON_DEV_WEB eliminado.
user CC_MANIF_BUILD eliminado.
user CC_SCHWEPPES_PLAY_INT_OWN eliminado.
user CCV_NATAL_INT_OWN eliminado.
user CSB_SCHWEPPES_TST_WEB eliminado.
user CCF_SAAC_DEV_WEB eliminado.
user CCF_COLETIVO_DEV_WEB eliminado.
user SPATIAL_CSW_ADMIN_USR eliminado.
user PROMOMUSICAOLD eliminado.
user CNC_BRN_MAG_DEV_OWN eliminado.
user CROWDPERFTSTOWN eliminado.
user CC_KUAT_HISTORY_INT_WEB eliminado.
user CSB_FANTA_AVENTURA_TST_WEB eliminado.
user CCV_PROMO_MUSIC_DEV_WEB eliminado.
user CC_CCZRIR_INT_OWN eliminado.
user CC_CONFCUP_WEB_TST eliminado.
user PEMBERTON_HOM_TST_WEB eliminado.
user DLV_TRADEMARK_TST_WEB eliminado.
user CCVCUP3_BUILD eliminado.
user CROWDPERFDEVWEB eliminado.
user CCV_MOBILE_BUILD eliminado.
user CCV_CUP_COLOR_DEV_OWN eliminado.
user CC_CCZRIR_INT_WEB eliminado.
user CCPEMBERTON eliminado.
user CC_STICKER_TST_OWN eliminado.
user CCV_NATAL_TST_WEB eliminado.
user CC_STICKER_DEV_OWN eliminado.
user FLOWS_FILES eliminado.
user BKP_CARREGADORES eliminado.
user CCF_COLETIVO_INT_WEB eliminado.
user CCV_MOBILE_INT_WEB eliminado.
user CCF_SAAC_TST_WEB eliminado.
user PROMOMUSIC_TST_OWN eliminado.
user CCV_WORLD_CUP_BUILD eliminado.
user CC_MANIF_DEV_WEB eliminado.
user CCV_CUP_COLOR_TST_OWN eliminado.
user CCF_SAAC_BUILD eliminado.
user CROWDPERFDEVOWN eliminado.
user CCF_PREMIO_PEMBERTON_TST_WEB eliminado.
user CCZSHAREOWN eliminado.
user CCF_PREMIO_PEMBERTON_INT_WEB eliminado.
user CC_TRIPS_TST_WEB eliminado.
user CC_CCZRIR_TST_OWN eliminado.
user CCVCUP3_DEV_WEB eliminado.
user CC_CONFCUP_BUILD eliminado.
user CC_SCHWEPPES_PLAY_DEV_WEB eliminado.
user CCF_PREMIO_PEMBERTON_BUILD eliminado.
user CC_LIVEPOSITIVELY_TS eliminado.
user CC_CCZRIR_DEV_WEB eliminado.
user DLV_TRADEMARK_DEV_WEB eliminado.
user CCV_COVERMIX_MOTHER_BUILD eliminado.
user CC_CONFCUP_OWN_TST eliminado.
user CCV_WORLD_CUP_TST_OWN eliminado.
user CCV_WORLD_CUP_INT_OWN eliminado.
user CCVCUP3_INT_OWN eliminado.
user PROMOMUSIC_INT_WEB eliminado.
user CCV_WORLD_CUP_TST_WEB eliminado.
user CCF_SAAC_INT_WEB eliminado.
user CCV_CUP_COLOR_INT_WEB eliminado.
user CCV_XMAS_TRIP_TST_OWN eliminado.
user CROWDPERFINTOWN eliminado.
user CCVLIVDONWEB eliminado.
user CCF_PREMIO_PEMBERTON_DEV_OWN eliminado.
user DLV_TRADEMARK_DEV_OWN eliminado.
user PEMBERTON_HOM_INT_WEB eliminado.
user CC_CCZRIR_TST_WEB eliminado.
user CCV_XMAS_TRIP_BUILD eliminado.
user CCV_WORLD_CUP_INT_WEB eliminado.
user CC_KUAT_HISTORY_TST_OWN eliminado.
user CCVCUP3_INT_WEB eliminado.
user COLETIVO_DUMP_PROD eliminado.
user CC_KUAT_HISTORY_INT_OWN eliminado.
user CCV_COVERMIX_MOTHER_TST_WEB eliminado.
user CCV_WORLD_CUP_DEV_WEB eliminado.
user CROWDPERFTSTWEB eliminado.
user DLV_TRADEMARK_INT_WEB eliminado.
user CCV_XMAS_TRIP_TST_WEB eliminado.
user CCF_COLETIVO_INT_OWN eliminado.
user CCV_WORLD_CUP_DEV_OWN eliminado.